import Head from "next/head";
import Header from "./components/Header";
import Footer from "./components/Footer";
import AboutMe from "./components/AboutMe";
import Services from "./components/Services";
import Portofolio from "./components/Portofolio";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false)
  const handleDarkMode = () => {
    setDarkMode(!darkMode)
  }
  console.log(darkMode)
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Nico Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-10 min-h-screen bg-white md:px-20 lg:px-40 dark:bg-gray-900 dark:text-white">
        {/* Navbar and heading component */}
        <Header setDarkMode={handleDarkMode}/>
        {/* About me component */}
        <AboutMe />
        {/* Services content component */}
        <Services />
        {/* Portofolio content component */}
        <Portofolio />
        {/* Footer components */}
        <Footer />
      </main>
    </div>
  );
}
