import Head from "next/head";
import Header from "./components/Header";
import Footer from "./components/Footer";
import AboutMe from "./components/AboutMe";
import Content from "./components/Content";

export default function Home() {
  return (
    <>
      <Head>
        <title>Nico Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-10 min-h-screen bg-white">
        {/* Navbar and heading component */}
        <Header />
        {/* About me component */}
        <AboutMe />
        {/* Main content component */}
        <Content />
        {/* Footer components */}
        <Footer />
      </main>
    </>
  );
}
